
services:
  ims:
    container_name: ims
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --config gunicorn-cfg.py core.wsgi"
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - ims
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 