# Generated by Django 4.1.12 on 2024-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_accountdetail_accountnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='accountnum',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
