# Generated by Django 4.1.12 on 2024-04-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_sales_foodsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsales',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
